openapi: 3.0.3
info:
  title: YellowFox Simulator API
  version: "0.1.0"
  description: Simulation von YellowFox-Endpunkten für Entwicklung/Tests.
servers:
  - url: https://YOUR-VERCEL-URL
security:
  - OAuth2ClientCreds: []
components:
  securitySchemes:
    OAuth2ClientCreds:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /api/oauth/token
          scopes: {}
  parameters:
    p_from: { name: from, in: query, schema: { type: string, format: date-time } }
    p_to:   { name: to,   in: query, schema: { type: string, format: date-time } }
    p_limit:{ name: limit,in: query, schema: { type: integer, minimum: 1, maximum: 1000, default: 100 } }
    p_cursor:{ name: cursor,in: query, schema: { type: string } }
paths:
  /api/oauth/token: { post: { summary: Client Credentials, responses: { "200": { description: OK } } } }
  /api/vehicles:    { get: { summary: Liste Fahrzeuge, responses: { "200": { description: OK } } } }
  /api/drivers:     { get: { summary: Liste Fahrer,    responses: { "200": { description: OK } } } }
  /api/positions:   { get: { summary: Positionspunkte, responses: { "200": { description: OK } } } }
  /api/trips:       { get: { summary: Fahrten,         responses: { "200": { description: OK } } } }
  /api/events:      { get: { summary: Events,          responses: { "200": { description: OK } } } }
  /api/webhooks/subscriptions: { post: { summary: Webhook registrieren, responses: { "201": { description: Created } } } }
  /api/webhooks/test:          { post: { summary: Test-Webhook,         responses: { "204": { description: No Content } } } }
